### ISSUE TITLE
name check is tricky

### ISSUE THREAD

**Issue by runcom** [projectatomic/oci-systemd-hook#25]
see https://bugzilla.redhat.com/show_bug.cgi?id=1375661

is there any other way to enable this w/o relying on `init` or `systemd`? @mrunalp @rhatdan ?

**Comment by mrunalp** [comment]
Can't really assume anything about an image. So I think better docs should be the fix here.

**Comment by runcom** [comment]
> Can't really assume anything about an image. So I think better docs should be the fix here.

right

**Comment by rhatdan** [comment]
But where should these docs exists?  Should we add information to docker run man pages?  Docker Build?
If this user noticed the difference where would he look to figure out what is going on?  Perhaps we should write more information to the log file saying oci-systemd-hook sees that you are running an init system as pid1 so it is mounting tmpfs on /run.  If we had the automatic cp feature from the underlying /run onto the tmpfs, would the user have noticed?

**Comment by rhatdan** [comment]
Closing this as I believe it is resolved.
