### ISSUE TITLE
support `readonly: false` containers

### ISSUE THREAD

**Issue by pschiffe** [projectatomic/oci-systemd-hook#37]
When trying to use rw rootfs:
```
$ sudo runc run ga
process_linux.go:330: running prestart hook 1 caused "exit status 1: "
```

```
...
    "root": {
        "path": "rootfs",
        "readonly": false
    },
...
    "hooks": {
        "prestart": [
            {
                "path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
            },
            {
                "path": "/usr/libexec/oci/hooks.d/oci-register-machine"
            }
        ],
        "poststop": [
            {
                "path": "/usr/libexec/oci/hooks.d/oci-systemd-hook"
            },
            {
                "path": "/usr/libexec/oci/hooks.d/oci-register-machine"
            }
        ]
    },
...
```

**Comment by rhatdan** [comment]
Are you running an init system or is this blowing up in general?

**Comment by pschiffe** [comment]
I'm running systemd inside of the container, but the error is the same even when I try to run something else (and change the process.args in config file).

**Comment by rhatdan** [comment]
Shouldn't this be true?
        "readonly": false

**Comment by pschiffe** [comment]
With `"readonly": true` it works correctly, but there are use cases when we need to write to the root fs. Specifically, in my use case, I need to create users in system container on the host during runtime. When I bind mount all needed files (/etc/passwd|shadow|group..) I still can't do it, because addgroup and adduser utilities create temporary files like /etc/group.13 and so on, during the user addition.

I'm working on Google Cloud Engine support tools for atomic host. These tools include some daemons which communicate with GCE metadata servers and get information about users and their public keys at any time.

**Comment by rhatdan** [comment]
Ok, I read this exactly wrong then you are saying oci-systemd-hook does not work with a read/write container image?  Weird since this is the way it works with Docker.

**Comment by pschiffe** [comment]
Yes, read/write container with Docker works, but not with runc.

**Comment by rhatdan** [comment]
@mrunalp Any ideas?

**Comment by mrunalp** [comment]
@pschiffe What rootfs are you using?

**Comment by pschiffe** [comment]
@mrunalp my sources are here: https://github.com/pschiffe/gce-system-container/tree/master/image (but now there is `readonly: true`, you need to change that to reproduce)
and from that directory I run:
`sudo docker build -t ga .; sudo atomic pull --storage ostree docker:ga; sudo atomic uninstall ga; sudo atomic install --system ga; sudo systemctl start ga`

**Comment by giuseppe** [comment]
are these users supposed to persist on the system (i.e. use the host /etc)?  Could an overlayfs over /etc in the container help?

**Comment by pschiffe** [comment]
Yes, the users are supposed to persist on the host, or at least, it must be possible to ssh with that users to the host. Overlayfs might not work, because of how adduser/group utilities work. They create new temp file e.g. /etc/group+ and then they move it to the original file /etc/group. This doesn't work when /etc/group is bind mounted from the host. So I'm thinking about chroot (RootDirectory in systemd unit) for the service managing users with /etc from the host and binaries from the container, but I didn't test that yet.

**Comment by giuseppe** [comment]
if you need that the users are visible on the host, why not bind mount /etc from the host?

**Comment by pschiffe** [comment]
This won't work because of systemd running inside of the container. When it sees the configuration of the host, it tries to do all the stuff systemd on the host is doing (setting network, mounts, sysctl..) And with single /etc dir shared with host and container, it's not possible to adjust it just for the container.

**Comment by giuseppe** [comment]
@pschiffe: I will take a look.  Iam not familiar with GCE.  How do I easily reproduce the problem with your image wrt creating new users?  Is it possible to create an arbitrary number of users?  Will they be removed when the container is uninstalled?

**Comment by giuseppe** [comment]
I see that you are creating a chroot for running the service in.

I saw that upstream systemd has a way to include mount points for a service https://github.com/systemd/systemd/pull/4727

While this is not yet usable for us, we could probably use something like this in the systemd unit file:
```
ExecStart=/usr/bin/run-in-host /usr/bin/google_accounts_daemon
MountFlags=slave
```

where the script `/usr/bin/run-in-host` looks like:

```
#!/bin/sh
mount --rbind /HOST/etc/ /etc/
mount --rbind /HOST/home /home/
mount --rbind /HOST/var/spool/mail /var/spool/mail
mount --rbind /HOST/var/log/lastlog /var/log/lastlog
mount --rbind /HOST/var/lib/google /var/lib/google
exec $@
```

Once the new systemd `BindPaths=` directive is available in Fedora we can drop the script and use only `BindPaths` from the systemd unit file.  What do you think?

I have not tried it on GCE, I've only tested it by replacing `google_accounts_daemon` with `adduser`.

**Comment by pschiffe** [comment]
@giuseppe hey! I've implemented your suggested change - https://github.com/pschiffe/gce-system-container/commit/7a458efb964f8ac7118d4f95808e844918fc6c6c It's working in GCE just fine. Thanks.

**Comment by giuseppe** [comment]
@pschiffe great!  What do you think about adding this system container to https://github.com/projectatomic/atomic-system-containers?

@rhatdan what do you think?  Would it fit there?

**Comment by pschiffe** [comment]
@giuseppe It's possible the image is not complete yet. I still need to do more tests. Also, what about the latest oci-systemd-hook and oci-register-machine packages? They need to be released, and also, the updated selinux policy. BTW, what is the latest atomic host? Fedora or CentOS? I need to test it there too. We will need to support the GCE system image on rhel atomic host, sooner the better.

**Comment by giuseppe** [comment]
@pschiffe the most updated version is CentOS Atomic Host Continuous, these changes will land on Fedora eventually and on RHEL->CentOS:

https://wiki.centos.org/SpecialInterestGroup/Atomic/Devel

**Comment by rhatdan** [comment]
I'm fine with adding it to atomic-system-containers.
