### ISSUE TITLE
Explain security of rw mount

### ISSUE THREAD

**Issue by kladkogex** [projectatomic/oci-systemd-hook#45]
We are considering to run this in our production environment, but there is a concern about 
security.

Is mounting of the host cgroups file read only / read-write into the container secure?

Can one use this functionality to hack into the host system in some way?

**Comment by rhatdan** [comment]
The only directory you could write to is the systemd subgroup.  There is a potential of a information leak, since cgroups is not namespaced.   Processes inside of the container could see pids of other processes on the host. This only is used when running systemd inside of the container.

**Comment by mrunalp** [comment]
We may be able to fix this by mounting the named systemd cgroup heirarchy per container.

**Comment by rhatdan** [comment]
I think this has been answered.
