### ISSUE TITLE
Recent changes to /var/log mounting breaks containers expecting build to populate /var/log

### ISSUE THREAD

**Issue by hogarthj** [projectatomic/oci-systemd-hook#46]
Since #42 has been merged I figured it best to open a separate issue to track this.

This affects both RHEL and Fedora with that commit.

Steps to replicate:

```
cat > Dockerfile.mariadb << EOF
FROM centos:latest
STOPSIGNAL SIGRTMIN+3
 
RUN yum -y install mariadb-server && yum clean all
 
RUN systemctl enable mariadb
 
VOLUME /var/lib/mysql
 
CMD ["/sbin/init"]
EOF
 
docker volume create --name localtest-mdb
docker build -f Dockerfile.mariadb -t localtest-mdb .
docker run -dt -v localtest-mdb:/var/lib/mysql --name localtest-mdb localtest-mdb
docker exec -t localtest-mdb /bin/bash -c 'for i in {1..30}; do if systemctl is-active mariadb ; then break  ; else sleep 1 ; fi done;'
docker exec -t localtest-mdb mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'%' IDENTIFIED BY 'testpassword' WITH GRANT OPTION;"
docker stop localtest-mdb
docker rm localtest-mdb
```

The mariadb service in the container after the container is started with docker run is expected to start successfully but it fails instead with the error /var/log/mariadb does not exist.

This directory was created via the mariadb-server rpm in the docker build but then does not get transferred into the /var/log tmpfs created by the hook.

This breaks any service that expects /var/log/<something> to already exist when run in a container using systemd and the hook.

**Comment by hogarthj** [comment]
I've carried out some further investigation and though I thought it was #42 at the time just reverting that code doesn't get back to a working system.

Looking through the git history between the previous rhel/fedora build and present #35 was also merged and that also plays around with this stuff.

I also have a simpler reproducer now as well:

``` 
cat > Dockerfile << EOF
FROM centos:latest

RUN yum -y update && yum -y install systemd && yum clean all
RUN mkdir /var/log/mydirhere && touch /var/log/mydirhere/mylogfile

CMD ["/sbin/init"]
EOF

docker build -t logtest .
docker run -dt logtest
docker exec -t logtest ls /var/log
```

With the older builds you'd see the directory and file from the docker build in /var/log but not with the current build.

**Comment by hogarthj** [comment]
Actually reading through the segment at line 377:

```
377  /* Move other user specified mounts under PATH to temporary directory */
378     for (unsigned i = 0; i < config_mounts_len; i++) {
379       /* Match destinations that begin with PATH */
380       if (!strncmp(path, config_mounts[i], strlen(path))) {
381         if (move_mount_to_tmp(rootfs, tmp_dir, config_mounts[i], strlen(path)) < 0) {
382           pr_perror("Failed to move %s to %s", config_mounts[i], tmp_dir);
383           return -1;
384         }
385       }
386     }
```

It looks like this ignores anything put in /var/log during the docker build at all? This will break anything that assumes rpm has created log directories with the right owners etc ...

In fact a quick check of httpd shows the same problems as mariadb:

```
httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-02-03 18:11:44 UTC; 15s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 58 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=1/FAILURE)
  Process: 57 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=1/FAILURE)
 Main PID: 57 (code=exited, status=1/FAILURE)

Feb 03 18:11:44 fcd1e4ffc67a systemd[1]: Starting The Apache HTTP Server...
Feb 03 18:11:44 fcd1e4ffc67a httpd[57]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
Feb 03 18:11:44 fcd1e4ffc67a httpd[57]: (2)No such file or directory: AH02291: Cannot access directory '/etc/httpd/logs/' for main error log
```

Note that with httpd /etc/httpd/logs is a symlink to /var/logs/httpd in a default install so these changes to make /var/log tmpfs are breaking a lot of standard builds

**Comment by hogarthj** [comment]
Does /var/log really need to be mounted to tmpfs without copying anything by default?

Just removing it from the tmpfs fixes the regression:
```
diff --git a/src/systemdhook.c b/src/systemdhook.c
index 6dcff09..5598f2e 100644
--- a/src/systemdhook.c
+++ b/src/systemdhook.c
@@ -492,11 +492,6 @@ static int prestart(const char *rootfs,
        snprintf(tmp_dir, PATH_MAX, "%s/tmp", rootfs);
 
        if (!contains_mount(config_mounts, config_mounts_len, "/var/log/journal")) {
-               /* Mount tmpfs at /var/log for systemd */
-               rc = move_mounts(rootfs, "/var/log", config_mounts, config_mounts_len, options);
-               if (rc < 0) {
-                       return rc;
-               }
 
                char journal_dir[PATH_MAX];
                snprintf(journal_dir, PATH_MAX, "/var/log/journal/%.32s", id);
```

If this is actually needed then the directories and files in the real /var/log will need to be copied into the tmpfs one for many different services to work, otherwise this will break many workloads.

**Comment by rhatdan** [comment]
Is the latest code still broken, or has it been fixed?

**Comment by hogarthj** [comment]
Literally just did a fresh build from HEAD to test and /var/log is not populated with what was in there before it got put on tmpfs ...

The reduced test case above shows no files in /var/log earlier (such as anaconda or yumlog which is are good ones to look for on an automated test) or for my mydirhere or the file to be present.

**Comment by rhatdan** [comment]
Ok thanks we will look at this on Monday.

@mrunalp I think we put this change in for Read Only containers, being able to create tmpfs on /var/log.  Which covers over the content underneath.   We can change this so it can check if /var/log/journal exists we mount on it, if it does not exist, we attempt to create it, if this fails, we just report it and continue without creating the journal directory.  I am not sure if systemd will handle this correctly but it should fail if it can not run without a journal.

**Comment by hogarthj** [comment]
I'm pretty sure that without a /var/log/journal then journald will use /var/run/journal 

I'm unsure why there's even a need for this in R/O containers as if a writeable /var/log is required for anything in such a container then surely passing in --tmpfs as a /var/log (or a persistent volume) would be a better solution than making this sort of invasive change in all containers?

I tried to look into what it would take to do a move of the underlying filesystem into the temp location before the atomic move operation from tmp to /var/log but it doesn't look too be a nice process in c++

**Comment by rhatdan** [comment]
Well this change should only happen in "init" or "systemd" containers but I agree this is a big bug.

**Comment by rhatdan** [comment]
Totally untested, but I think this might be a better solution.
https://github.com/projectatomic/oci-systemd-hook/pull/47

**Comment by rhatdan** [comment]
We could look at also mount the external log file at /var/run/journal, if this issue happens and see if systemd writes the log externally.  Since /var/run will be a tmpfs.

**Comment by hogarthj** [comment]
Isn't #if 0 <foo> #endif going to run the code in <foo> anyway which will still do the tmpfs /var/log mount over the real log dir?

I'd probably think about trying to just mount /var/log/journal but I'm unsure what interaction that would have of providing a persistent volume (or --tmpfs) for /var/log in terms of timing for the mounting and any race conditions as a result.

As for this change only happening in systemd containers ... That's the majority of time I'd imagine this being a problem anyway as that's the best way of handling services with child processes that need management or reaping such as with httpd or mariadb (as the two things I bumped into specifically) ... Or any similar service that have children that may need reaping and expect their log directory to already exist on start.

For now in my workplace I've rolled out a patched version that just skips the tmpfs mounting of just /var/log to allow the containers we run to function as previously.

Is it feasible perhaps to test if /var/log is r/o and only engage this behaviour in that instance?

This does, of course in the case of docker as I've not looked into other container behaviour, not act consistently with providing a volume as doing that will copy the underlying files into it whilst mounting it unlike this which just overlays on top and prevents access to the original files.

**Comment by rhatdan** [comment]
No 
```
#if 0
<foo>
#endif
```
Will ignore all code in the block.

oci-systemd-hook happens before systemd starts, so there is no race condition.

Please try out my latest patch to see if this fixes your problem,  And I will look into on Monday also doing the mount point on /var/run/journal if the mkdir fails.

**Comment by hogarthj** [comment]
My c++ knowledge is rather limited in sure you can tell... Live mostly in python ;)

But does it run before or after runc/rkt/docker/etc mount any volumes into place via -v or --tmpfs (or equivalent)?

Normally it's just not an issue but I'm trying to think of any ordering problems surrounding /var/log and the journal directory in it if oci is handling the latter and runc/docker/etc is handling the former.

I've got some house chores to do but I'll compile with this patch and run my tests a little later this weekend.

**Comment by rhatdan** [comment]
This code runs inside of runc, after the container is setup.  It should preserve ordering on volumes mounted into the container.  The last fix we did was to preserve mounts of other file systems on /var/log/foobar.  But this fix did not fix the problem where content was created in /var/log/foobar in the image, so it was still a bug.

I pushed an update to my patch to attempt to mount on /run/log/journal if /var/log/journal is not able to be mounted on/written too.

**Comment by hogarthj** [comment]
So I just built master/HEAD from this repo with your patch from #47 applied on top and the container behaves as expected.

Systemd is starting mariadb/httpd correctly and my reduced testcase work fine.

**Comment by mrunalp** [comment]
I will test it out once tomorrow and merge. Thanks!

**Comment by rhatdan** [comment]
I was thinking about this more yesterday, and I think we need to further fix this. 
Basically we could mount a tmpfs on /var/log/journal if it existed and was read/only rather then at /var/log.
This would give us another option

Steps
Try to create ROOTFS /var/log/journal/UUID if it does not exist.  If fails, try to create ROOTFS/var/log/journal, if it exists mount tmpfs and create /var/log/journal/UUID
If it does not move to /run/journal/UUID.

**Comment by mrunalp** [comment]
> Try to create ROOTFS /var/log/journal/UUID if it does not exist. If fails, try to create ROOTFS/var/log/journal, if it exists mount tmpfs and create /var/log/journal/UUID
If it does not move to /run/journal/UUID.

I didn't get the last step, move what to /run/journal/UUID?

**Comment by rhatdan** [comment]
If I can't write to /var/log/journal then systemd will not be able to either so we create the mount point on /run/journal/UUID and supposedly systemd will write the journal information there.

**Comment by mrunalp** [comment]
@rhatdan Ah, okay. Thanks!

**Comment by robert-scheck** [comment]
The recent changes breaking e.g. MariaDB also seem to affect the SELinux policy, at least I didn't see that before the breaking update in RHEL 7.3: https://bugzilla.redhat.com/show_bug.cgi?id=1423502

**Comment by rhatdan** [comment]
This should be fixed with the latest package.
