### ISSUE TITLE
cgroup remount avc when running systemd container

### ISSUE THREAD

**Issue by qiancai** [projectatomic/oci-systemd-hook#53]
Using the latest master of git + RHEL 7.3.3. This is fixed in RHBZ#1439382, but still present in the latest upstream master git.

`# docker run -d  rhel7 init`
`# ausearch -m AVC`
`----
time->Wed Apr  5 16:36:37 2017
type=SYSCALL msg=audit(1491424597.983:276): arch=c000003e syscall=165 success=no exit=-13 a0=55f7275fcad2 a1=55f7275f8ce0 a2=55f7275fcad2 a3=100002f items=0 ppid=13067 pid=13086 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd" exe="/usr/lib/systemd/systemd" subj=system_u:system_r:svirt_lxc_net_t:s0:c11,c931 key=(null)
type=AVC msg=audit(1491424597.983:276): avc:  denied  { remount } for  pid=13086 comm="systemd" scontext=system_u:system_r:svirt_lxc_net_t:s0:c11,c931 tcontext=system_u:object_r:svirt_sandbox_file_t:s0:c11,c931 tclass=filesystem
----`

Looks like the cgroup mount is messed up.
`# diff -u /tmp/good /tmp/bad`
`--- /tmp/good	2017-04-10 10:23:39.945725760 -0400`
`+++ /tmp/bad	2017-04-10 10:22:42.046725760 -0400`
```
- tmpfs on /sys/fs/cgroup type tmpfs (ro,relatime,seclabel,mode=755)
-cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
-cgroup on /sys/fs/cgroup/memory type cgroup (ro,relatime,memory)
-cgroup on /sys/fs/cgroup/blkio type cgroup (ro,relatime,blkio)
-cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,relatime,cpuacct,cpu)
-cgroup on /sys/fs/cgroup/devices type cgroup (ro,relatime,devices)
-cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,relatime,net_prio,net_cls)
-cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,relatime,hugetlb)
-cgroup on /sys/fs/cgroup/pids type cgroup (ro,relatime,pids)
-cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,relatime,perf_event)
-cgroup on /sys/fs/cgroup/freezer type cgroup (ro,relatime,freezer)
-cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,relatime,cpuset)
+cgroup on /sys/fs/cgroup/systemd type cgroup (ro,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
+cgroup on /sys/fs/cgroup/systemd/system.slice/docker-170545ba00877062942beb8146971906363b34d278f7117262814e92ae2baa22.scope type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)```

**Comment by rhatdan** [comment]
This should be fixed with the current container-selinux package.
