### ISSUE TITLE
Mounting the docker socket inside a container does not work

### ISSUE THREAD

**Issue by nightvisi0n** [projectatomic/oci-systemd-hook#72]
I'm trying to mount the docker socket of my host machine into a docker container:  
```
docker run -it --rm --privileged -v /run/docker.sock:/run/docker.sock [...]
```
This works like a charm without oci-systemd-hook.  

Unfortunately the container does not start with oci-systemd-hook:  
```
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:334: running prestart hook 2 caused \"error running hook: exit status 1, stdout: , stderr: \"".
```

journalctl extract:
```
Aug 04 11:21:21 leo oci-systemd-hook[11861]: systemdhook <debug>: rootfs=/var/lib/docker/btrfs/subvolumes/ef68e2c17a956a8fd7b0e8d1def13c2454fadd4aa8ccae1b6198fd113c882ca0
Aug 04 11:21:21 leo oci-systemd-hook[11861]: systemdhook <debug>: gidMappings not found in config
Aug 04 11:21:21 leo oci-systemd-hook[11861]: systemdhook <debug>: GID: 0
Aug 04 11:21:21 leo oci-systemd-hook[11861]: systemdhook <debug>: uidMappings not found in config
Aug 04 11:21:21 leo oci-systemd-hook[11861]: systemdhook <debug>: UID: 0
Aug 04 11:21:21 leo oci-systemd-hook[11861]: systemdhook <error>: Failed to move mount /var/lib/docker/btrfs/subvolumes/ef68e2c17a956a8fd7b0e8d1def13c2454fadd4aa8ccae1b6198fd113c882ca0//run/docker.sock to /tmp/ocitmp.sr55QE//docker.sock: I
Aug 04 11:21:21 leo oci-systemd-hook[11861]: systemdhook <error>: Failed to move /run/docker.sock to /tmp/ocitmp.sr55QE: Invalid argument
```

I'm running `oci-systemd-hook-0.1.11-1.git1ac958a.fc26.x86_64` on Fedora 26.  
I could reproduce this also on Fedora 25 with `oci-systemd-hook-0.1.6-1.gitfe22236.fc25.x86_64`.  

If you require any further information, I will be happy to provide it.

**Comment by rhatdan** [comment]
Are you running init or systemd inside of the container?

**Comment by nightvisi0n** [comment]
I'm running systemd inside the container (also fedora 26 based).

**Comment by rhatdan** [comment]
Ok, maybe the code is not handling sockets correctly.

**Comment by rhatdan** [comment]
This is the code that is failing.

	if ((mount(src, dest, "", MS_MOVE, "") == -1)) {
		pr_perror("Failed to move mount %s to %s", src, dest);
		return -1;
	}
Perhaps you can not move a unix domain socket?

**Comment by rhatdan** [comment]
Ok I attempted to get this to happen on my host without containers.

sh-4.4# touch /tmp/docker.sock
sh-4.4# mount -o bind /run/docker.sock /tmp/docker.sock
sh-4.4# mount -t tmpfs none /mnt
sh-4.4# touch /mnt/docker.sock
sh-4.4# mount --move /tmp/docker.sock /mnt/docker.sock 
mount: /mnt/docker.sock: bad option; moving a mount residing under a shared mount is unsupported.
sh-4.4# mount --make-rprivate /
sh-4.4# mount --move /tmp/docker.sock /mnt/docker.sock 
sh-4.4#

So this works.

strace shows

mount("/mnt/docker.sock", "/tmp/docker.sock", 0x55e629506f20, MS_MGC_VAL|MS_MOVE, NULL) = 0

I have no idea what the 0x55e629506f20 is, but maybe we should be useing MS_MGC_VAL?

@mrunalp @nalind @rhvgoyal  Any ideas?

**Comment by rhatdan** [comment]
man 2 mount
...
      The mountflags argument may have the magic number  0xC0ED  (MS_MGC_VAL)
       in  the top 16 bits (this was required in kernel versions prior to 2.4,
       but is no longer required and ignored if specified), and various  mount
       flags in the low order 16 bits:

So MS_MGC_VAL does not seem important.

**Comment by rhatdan** [comment]
The special value in the filesystem flag does not seem to matter.
       MS_MOVE
              Move a subtree.  source specifies an existing  mount  point  and
              target  specifies  the  new location.  The move is atomic: at no
              point is the subtree unmounted.  The filesystemtype, mountflags,
              and data arguments are ignored.

**Comment by rhvgoyal** [comment]
@rhatdan I have seen this restriction of parent mount not allowed to be `shared` with pivot_root() as well. And vaguely remember reading similar restrictions for MS_MOVE.

Not sure if this is imposed for source or destination or both. Not sure why are we moving a mount. But if we are, then let us make sure it is not `shared`

**Comment by rhatdan** [comment]
We mount a tmpfs onto /run, which is something systemd requires, but if the user has mounted anything on /run, then we need to MS_MOVE it to some other directory, mount the tmpfs and then MS_MOVE It back.  Do you think if we mounted these mount points as PRIVATE, this issue would go away?

**Comment by rhvgoyal** [comment]
I suspect mounting /run as private might solve the issue. Give it a try.

**Comment by rhatdan** [comment]
Well I just created a pull request https://github.com/projectatomic/oci-systemd-hook/pull/73, have not tested it yet to see if it fixes the issue.

**Comment by nightvisi0n** [comment]
The fix works for me.  
Thanks for the fast fix and for the update of the update of according fedora packages! :+1:
