### ISSUE TITLE
invalid machine-id

### ISSUE THREAD

**Issue by brahim-raddahi** [projectatomic/oci-systemd-hook#89]
The new function shortid which has been introduced for logging purposes (I think), causes the id which is passed to the "prestart" function to be only 12 characters long, this is what is eventually written to "/etc/machine-id" in the container.

Now, if systemd inside the spawned container tries to read this id, it regards it as "invalid", because it's not long enough, resulting in this message in this boot message:

> Initializing machine ID from random generator.

The result is that a new machine-id is created on every boot and the journal is written to that directory (so it's not ending up in the mounted /var/log/journal/machine-id directory on the host).

I think we end up here:
https://github.com/systemd/systemd/blob/master/src/core/machine-id-setup.c
at the line that says:

> * Hmm, so, the id currently stored is not useful, then let's generate one */

If I change this:

> return strndup(id, 12);

to this:

> return strndup(id, 32);

then it is accepted as a valid machine-id and the message "Initializing machine ID from random generator." disappears ...

So I guess this requires a little bit of refactoring to still have a shortid for logging purposes and a valid machine-id at the same time

**Comment by rhatdan** [comment]
Is this something you are going to work on or do you want us to?

**Comment by rhatdan** [comment]
@mrunalp @runcom FYI

**Comment by rhatdan** [comment]
@brahim-raddahi This change, was that in runc?

**Comment by brahim-raddahi** [comment]
The change was in the hook itself

I think this commit introduced it: https://github.com/projectatomic/oci-systemd-hook/commit/481054790faba0b2ed5a54f2e977efb10714d269#diff-806839eda2a67ce8a678542897899972

Do you want me to create a pull request?

**Comment by rhatdan** [comment]
Yes that would be great.
